n=input('Digite algo:')
print('Qual é o tipo primitivo?') 
print(type(n))
print('Tem espaço?') 
print(' ' in n)
print('É um número?')
print(n.isnumeric())
print('É alfabético?')
print(n.isalpha())
print('É alfanúmerico?')
print(n.isalnum())
print('Está em maiúsculas?')
print(n.isupper())
print('Está em minúsculas?')
print(n.islower())
print('Está capitalizada?')
print(n.istitle())