n=int(input('Digite um número para ver sua tabuada:'))
a='-'*12
b=('{:^3} x 1 = {:^3}'.format(n,n*1))
c=('{:^3} x 2 = {:^3}'.format(n,n*2))
d=('{:^3} x 3 = {:^3}'.format(n,n*3))
e=('{:^3} x 4 = {:^3}'.format(n,n*4))
f=('{:^3} x 5 = {:^3}'.format(n,n*5))
g=('{:^3} x 6 = {:^3}'.format(n,n*6))
h=('{:^3} x 7 = {:^3}'.format(n,n*7))
i=('{:^3} x 8 = {:^3}'.format(n,n*8))
j=('{:^3} x 9 = {:^3}'.format(n,n*9))
k=('{:^3} x10 = {:^3}'.format(n,n*10))
l='-'*12
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(i)
print(j)
print(k)
print(l)